export const _templateData: any = `<h1 style="text-align:center;"><span style="color:hsl(0,0%,0%);"><u>Consultant Agreement</u></span></h1><p><span style="color:hsl(0,0%,0%);">This Consultant Agreement is signed on&nbsp;</span><span class="placeholder">[Vendor Signed Date]</span><span style="color:hsl(0,0%,0%);">&nbsp;and is made effective from&nbsp;</span><span class="placeholder">[Start Date]</span><span style="color:hsl(0,0%,0%);">&nbsp;(<strong>“Start Date”</strong>) by and amongst:&nbsp;</span></p><ol style="list-style-type:upper-latin;"><li><span class="placeholder">[Company Name]</span><span style="color:hsl(0,0%,0%);">(CIN:&nbsp;</span><span class="placeholder">[Company Registration Number]</span><span style="color:hsl(0,0%,0%);">), a company incorporated in India, having its registered office at&nbsp;</span><span class="placeholder">[Company Full Address]</span><span style="color:hsl(0,0%,0%);">&nbsp;(hereinafter referred to as <strong>“Company”,</strong> which expression shall include its successors and permitted assigns);&nbsp;</span></li></ol><p style="text-align:center;"><span style="color:hsl(0,0%,0%);">&nbsp;</span><br><span style="color:hsl(0,0%,0%);"><strong>AND</strong>&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></p><ol style="list-style-type:upper-latin;" start="2"><li><span style="color:hsl(0,0%,0%);">Mr. / Ms.&nbsp;</span><span class="placeholder">[Vendor First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Vendor Last Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;(PAN:&nbsp;</span><span class="placeholder">[Vendor PAN]</span><span style="color:hsl(0,0%,0%);">) (<strong>“Consultant”</strong>) and currently residing at&nbsp;</span><span class="placeholder">[Vendor Full Address]</span><span style="color:hsl(0,0%,0%);">.&nbsp;&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol><p>&nbsp;</p><ol><li><span style="background-color:transparent;color:hsl(0,0%,0%);"><strong>P‌rovision of Services</strong></span><br><br><span style="background-color:transparent;color:hsl(0,0%,0%);">You will be responsible for the execution of the various assignments / tasks given to you from time to time and agreed upon as per the SOW. You will, at all times, abide by the rules and regulations framed from time to time by the Company.&nbsp;</span><br><br><span style="background-color:transparent;color:hsl(0,0%,0%);">For initiating any and every Services assignment (“Assignment”), the Parties shall enter into and execute a statement of work (“SOW”) in the form provided in Schedule I hereto mentioning the details of Assignment, description of Services, manner of performance, specifications, timelines, fee and other compensation (“Fee”) and manner of payment thereof and other relevant terms and conditions. Upon execution of the SOW, the Consultant shall commence providing Services under the Agreement towards completion of the Assignment in accordance with the SOW.‌</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Exclusivity</strong></span><br><br><span style="color:hsl(0,0%,0%);">You will not (without the prior written consent of the Company or such of its subsidiaries or associated companies as may be relevant) during your Consulting engagement, directly or indirectly be interested in, engage in, be concerned with, or provide services to, any other person, company, business entity or other organisation whatsoever (whether as an employee, officer, director, agent, partner, consultant or otherwise) it being the intention of the Company that you will devote your whole time and attention to the service of the Company. Violation of this provision will result in termination of your services.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Compensation to The Consultant</strong></span><br><br><ol style="list-style-type:lower-roman;"><li><span style="color:hsl(0,0%,0%);">The Parties agree that in consideration of the Consultant providing the Services to the Company, as agreed upon between Parties in the relevant SOW, the Consultant shall be entitled to such Fee as set forth in the SOWs agreed by the Parties in writing during the subsistence of the Agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The manner of payment of Fee shall be as per the SOW. The Fee shall be payable within a period of 15 from the receipt of an invoice from the Consultant.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The compensation detailed in Clause 3.1 above shall be due and payable to the Consultant only and only if the Consultant provides the Services in accordance with the scope and specifications mentioned in the SOW.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Consultant shall be entitled, on production of satisfactory evidence of expenditure to the Company, to be reimbursed by the Company for all reasonable out of pocket expenses incurred by the Consultant, with prior approval of the Company, pertaining to or in connection with the performance of his duties under this Agreement in line with the Company’s expenses policy.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">All payments made by the Company, shall be subject to statutory deductions under applicable Laws and any other deductions as maybe applicable. The Consultant shall be responsible and liable for all tax implications arising out of this Agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Consultant acknowledges that the compensation is confidential information between him/her and the company. Consequently, any unauthorized disclosure of this information is considered as violation of this agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol></li><li><span style="color:hsl(0,0%,0%);"><strong>Intellectual Property Rights</strong></span><br><br><span style="color:hsl(0,0%,0%);">Any and all intellectual property of any nature whatsoever that you may develop during the course of your engagement shall be the property of the Company, and you hereby agree that you shall co-operate fully with the Company in executing all such documents, and taking all such actions as may be necessary, to ensure the title and ownership of the Company to such intellectual property. You hereby waive any and moral rights that you may have in such intellectual property, and agree that the Company may use, adapt or exploit such intellectual property in any manner that the Company may, in its sole discretion, deem fit. You are required to adhere to the Company’s IT and Device Policy with respect to use of software, hardware, network and technology.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Conflict of Interest</strong></span><br><br><span style="color:hsl(0,0%,0%);">You agree to declare any and all business interest that you may be interested in, whether or not similar to or in conflict with the business or activities of the Company or its subsidiaries / associated companies, which you may be privy to or associated with in any manner, whether on the date hereof, or at any subsequent time during your engagement with the Company.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Restrictions on cessation of Consulting contract</strong></span><br><br><span style="color:hsl(0,0%,0%);">You shall not, within twelve (12) months after the date of termination of your consulting contract with the Company, recruit, solicit, entice, assist, or engage in any activity whatsoever that would result in any person then or thereafter employed by the Company or appointed as a representative of the Company, to join you in providing services to or be employed by any business activity in which you may be involved.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Non-Competition</strong></span><br><br><span style="background-color:transparent;color:hsl(0,0%,0%);">You acknowledge that during the course of your engagement with the Company, you will become familiar with the Company’s trade secrets and with other confidential information concerning the Company and its associates and related Companies and the customers/suppliers other business affiliates of the Company, its subsidiaries and/or affiliates, and that your services will be of a special, unique and extraordinary value to the Company. &nbsp;You agree that during the Term hereof you shall not directly or indirectly own, manage, control, participate in, consult with, render services for, or engage in any business competing with the businesses of the Company or its associates or related Companies within India. &nbsp;For the purpose of this Agreement, the “businesses of the Company” shall mean Skuad or any other business, which the company operates now or will operate in the future. You hereby specifically acknowledge and agree that the covenants and promises of the parties herein contained, and the offer of employment on the terms and conditions hereof, constitute valid and sufficient consideration for your promises and undertakings in this Clause. You will not disclose any confidential information you obtained during the engagement with the company to anybody outside during or after the completion of your consulting contract.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Personal Information</strong></span><br><br><span style="color:hsl(0,0%,0%);">The personal information you provide to the Company in connection with your recruitment and subsequent consulting engagement will be used for the purpose of administering your contract with the Company. The Company may give out some of this information to other parties authorised or required by law to receive it. We trust that the information provided to the Company at the time of your contract and as required subsequently will be true and accurate. In the event that any of the information provided by you is found to be incorrect, the Company reserves the right to terminate this Agreement. You also give consent to the Company for holding and processing, both electronically and manually, the data that it collects related to your employment for the purpose of its business and complying with Applicable Law. You also further give consent to the Company to disclose your personal data to any group companies, regulatory or governmental authority or any other third party where such disclosure is necessary for, or ancillary to, compliance with any applicable law.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Return of Company Property</strong></span><br><br><span style="color:hsl(0,0%,0%);">Upon the termination of your services with the Company for any reason whatsoever, or in any event that you are called upon to do so by the Company, you shall also deliver to the Company all company property, equipment and materials (including correspondence, tapes, drawings, notes, plans or other documents of whatsoever nature and all copies thereof) made or compiled or required by you during your engagement hereunder and concerning the business, finances or affairs of the Company or any member of the Group Companies.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Remedy</strong></span><br><br><span style="color:hsl(0,0%,0%);">Notwithstanding anything to the contrary in this contract, if you breach any provision of this contract, the Company shall have the right, subject to statute, to set-off against any sums the Company owes you the amount of any damages incurred or suffered by the Company as a result of the breach. Any such set-off shall not be presumed to be in full satisfaction of or as liquidated damages for or as a release of any claim or damages against you that may accrue to the Company as a result of the breach.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Non-disparagement</strong></span><br><br><span style="color:hsl(0,0%,0%);">You agree that you shall act with the highest standards of propriety and professionalism and shall not criticize, ridicule or make any statement which disparages or is derogatory of the company, any of its Group companies or any other employee or business associate of the Company or the Group Company in any public or non-public communication with any customer, client or member of the investment community or media or in any communication<strong>.</strong></span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Confidential nature of terms of Consulting engagement</strong></span><br><br><span style="color:hsl(0,0%,0%);">You agree that, except as may be required by applicable law you shall not disclose the terms of consulting engagement to any person other than your close family members.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Enforceability Rules, Regulations and Policy on Ethics</strong></span><br><br><span style="color:hsl(0,0%,0%);">You will be covered by the service rules and regulations including conduct, discipline and administrative orders and any such other rules or orders of the company that may come in force from time to time. You must observe the policies that the Company publishes from time to time. These include a requirement that you maintain the highest standards of conduct and act with the highest ethical principles.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Absenteeism</strong></span><br><br><span style="color:hsl(0,0%,0%);">lf you absent yourself without leave or remain absent beyond the period of leave originally granted or subsequently extended, you shall be considered as having voluntarily terminated your consulting engagement without giving any notice unless you:</span><br><br><ul><li><span style="color:hsl(0,0%,0%);">Return to work within 5 days from the commencement of such absence, and&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">Give an explanation lo the satisfaction of the Management regarding such absence</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ul></li><li><span style="color:hsl(0,0%,0%);"><strong>Enforceability</strong></span><br><br><span style="color:hsl(0,0%,0%);">You acknowledge and agree that any violation of any of your duties and responsibilities may result in irreparable damage to the Company, and, accordingly, the Company may obtain injunctive and other equitable relief for any breach or threatened breach of such duties and obligations, in addition to any other remedies available to the Company. You and the Company agree that the restrictions and remedies contained hereinabove are reasonable and that it is your intention and the intention of the Company that such restrictions and remedies shall be enforceable to the fullest extent permissible by law. lf it shall be found by a court of competent jurisdiction that any such restriction or remedy is unenforceable but would be enforceable if some parts thereof were deleted or the period or area of application reduced, then such restriction or remedy shall apply with such modification as shall be necessary to make it enforceable.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Representations And Warranties</strong></span><br><br><span style="color:hsl(0,0%,0%);">Each Party represents to the other Party that:</span><br><br><ol style="list-style-type:lower-roman;"><li><span style="color:hsl(0,0%,0%);">he / she / it has the power to enter into, perform and deliver and has taken all necessary action to authorise their entry into, performance and delivery of this Agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">he / she / it has taken independent legal advice in relation to entering into this Agreement and does so without any duress and with the full understanding of all his/ her / its obligations and liabilities hereunder.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">the obligations expressed to be assumed by him / her / it under this Agreement are legal, valid, binding and enforceable obligations, subject to applicable laws of insolvency, bankruptcy and equity.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol></li><li><span style="color:hsl(0,0%,0%);"><strong>Governing Law &amp; Dispute Resolution</strong></span><br><br><ol style="list-style-type:lower-roman;"><li><span style="background-color:transparent;color:hsl(0,0%,0%);">This Agreement shall be governed in all respects by the Laws of India (without reference to its conflict of Laws provisions).</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="background-color:transparent;color:hsl(0,0%,0%);">All disputes or differences between the Parties shall be resolved by final and binding arbitration at the request the disputing Parties upon written notice to that effect to the other disputing Parties. The arbitration shall be in accordance with the rules of the Indian Arbitration and Conciliation Act, 1996 (“<strong>Arbitration Act</strong>”) and the rules made there under, in force at the relevant time (which is deemed to be incorporated into this Agreement by reference). All proceedings of the arbitration shall be in the English language. The venue of arbitration shall be Gurgaon, Haryana, India. The dispute shall be referred to a single arbitrator, who shall be appointed by the Parties mutually. The decision of the arbitrator shall be final and binding on the Parties. Arbitration awards rendered shall be final, binding and shall not be subject to any form of appeal.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="background-color:transparent;color:hsl(0,0%,0%);">Subject to arbitration provision above, the Courts at Gurgaon, Haryana, India shall have exclusive jurisdiction for matters relating to this Agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol></li><li><span style="color:hsl(0,0%,0%);"><strong>Term and Termination</strong></span><br><br><ol style="list-style-type:lower-roman;"><li><span style="color:hsl(0,0%,0%);">This Agreement shall come into effect and be valid from the Effective Date and shall, shall remain valid unless terminated in accordance with provisions hereof (“Term”).</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Parties may terminate this Agreement at any time during the term of this Agreement by mutual agreement in writing.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">Unless otherwise provided in the SOW, each Party shall have right to terminate this Agreement at any time by providing a prior written notice of 30 to the other Party.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Parties agree that the Agreement the Company shall have the right to terminate the Agreement immediately with written notice to the Consultant, without any liability, if (i) the Consultant has committed or is guilty of a fraudulent conduct, a deliberate attempt to cause an injury to the Company, or conduct that discredits the Company or is detrimental to the reputation of the Company, including any criminal offence involving moral turpitude; (ii) the Consultant is guilty of neglect, dishonesty, insobriety, misconduct or commits any act which, in the opinion of the Company is contrary to the interests of the Company or Company’s policies; (iii) the Consultant commits a breach of any of the terms and conditions of his association with the Company.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">Termination of this Agreement for whatsoever reasons will be without prejudice to the right of either Party against each other than accruing or accrued in respect of the event giving rise to such termination or otherwise under this Agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol></li><li><span style="color:hsl(0,0%,0%);"><strong>Notices</strong></span><br><br><span style="color:hsl(0,0%,0%);">Each notice, demand or other communication given or made under this Agreement shall be in writing and delivered or sent to the relevant Party at the address or email id set out below (or such other address or email id number as the addressee has by five (5) Business Days' prior written notice specified). Any notice, demand or other communication so addressed to the relevant Party shall be deemed to have been delivered (a) if delivered in person or by messenger, when proof of delivery is obtained by the delivering Party, (b) if sent by post within the same country, on the fifth (5th) Business Day following posting, and (c) if given or made by email, upon delivery of the email.</span><br><br><span style="color:hsl(0,0%,0%);">The initial address for the Parties for the purposes of the Agreement are:</span><br><br><span style="color:hsl(0,0%,0%);">If to the <strong>Company:</strong></span><br><br><span style="color:hsl(0,0%,0%);"><strong>Attention:&nbsp;</strong></span><span class="placeholder">[Client First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Client Last Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Address:</strong>&nbsp;</span><span class="placeholder">[Company Full Address]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Email:</strong>&nbsp;</span><span class="placeholder">[Client Email]</span><br><br><span style="color:hsl(0,0%,0%);">If to <strong>Consultant:</strong></span><br><br><span style="color:hsl(0,0%,0%);"><strong>Address:&nbsp;</strong></span><span class="placeholder">[Vendor Full Address]</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Email:&nbsp;</strong></span><span class="placeholder">[Vendor Email]</span><br><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Miscellaneous Representations and Warranties</strong></span><br><br><ol style="list-style-type:lower-latin;"><li><span style="color:hsl(0,0%,0%);">You are under no contractual or other restriction or obligation which is inconsistent with the conditions contained herein, the performance of your duties hereunder, or the other rights of the Company hereunder;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">You shall not raise any issue on the reasonableness of the terms, covenants, and/or conditions in any proceeding to enforce these terms, covenants and/or conditions;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">You have full right and authority to execute this contract and that you are not bound by any contract or arrangement, including any employment contract, bond, or covenant not to compete, inconsistent herewith.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Consultant shall not be entitled to assign, sub-contract or outsource any right, duty or obligation under this Agreement in any manner whatsoever.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">You hereby agree and undertake to indemnify the Company, its affiliates and the directors, officers and employees of each of the foregoing and to hold them harmless from and against any and all third party claims they face, which give rise to any liabilities, damages, claims, costs and expenses (including legal expenses), due to any act, omission, violation or breach of any of your representations, warranties, and covenants.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">Amendment: This Agreement may not be amended, modified or supplemented except by a written instrument executed by each of the Parties.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Company shall indemnify and defend you to the fullest extent permitted by the law of the State of Company's incorporation and the By-Laws of the Company with respect to any claims that may be brought against you arising out of any action taken or not taken in your capacity as an officer or director of the Company; provided, that, the Company shall not indemnify and defend you with respect to any claims brought against you relating to intentional or wilful acts, or to other acts as to which indemnification is not allowable under applicable law.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">These terms, covenants, and/or conditions shall survive the termination of your consulting engagement with the Company, and the terms, covenants, and conditions set forth herein are essential for the Company's protection, and the Company has relied on these representation and warranties made by you.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">nothing contained in this Agreement shall be construed as creating a partnership or employer-employee relationship between the Company and the Consultant;&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">nothing contained in this Agreement or otherwise shall entitle the Consultant to claim employment with the Company or fees, benefits and compensation other than those mentioned in this Agreement; and&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">the Consultant shall not have any authority or right to make commitment on behalf of the Company or to bind the Company in any manner whatsoever, except where expressly permitted in writing.&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Consultant shall ensure that all the Services are rendered strictly in accordance with the specifications and timelines, if any, mentioned in the SOW. The Consultant shall provide all the Services strictly as per the protocols and parameters specified by the Company in writing from time to time.</span><br>&nbsp;</li><li><span style="background-color:#ffffff;color:hsl(0,0%,0%);">“The Agreement shall be co-terminus with the Company’s arrangement with the Client, and accordingly, by way of example and without limitation, the Consultant’s obligations under Section 10 and this Section 19 shall apply to both the Company and the Client.”</span><br>&nbsp;</li></ol></li></ol><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);">The various clauses of this agreement are to be read, understood, and interpreted in its entirety, and none of the clauses are severable from the remaining.&nbsp;</span><br><br><span style="color:hsl(0,0%,0%);">The terms and conditions specified herein are subject to change as per the Human Resource policy published / circulated by the company from time to time.&nbsp;</span><br><br><span style="color:hsl(0,0%,0%);">We look forward to a successful working relationship.</span></p><div class="page-break" style="page-break-after:always;"><span style="display:none;">&nbsp;</span></div><p style="margin-left:40px;"><br><span style="color:hsl(0,0%,0%);"><strong>IN WITNESS WHEREOF, THE PARTIES HAVE ENTERED INTO THIS AGREEMENT THE DAY AND YEAR FIRST ABOVE WRITTEN</strong></span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);">Signed and delivered for and on behalf of&nbsp;</span><span class="placeholder">[Company Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;by:</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span class="placeholder">[Client Signature]</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>Name:</strong>&nbsp;</span><span class="placeholder">[Client First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Client Last Name]</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Designation:</strong>&nbsp;</span><span class="placeholder">[Client Designation]</span></p><p style="margin-left:40px;"><br><span style="color:hsl(0,0%,0%);"><strong>Date:&nbsp;</strong></span><span class="placeholder">[Client Signed Date]</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);">Signed and delivered by the Consultant</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span class="placeholder">[Vendor Signature]</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>Name:&nbsp;</strong></span><span class="placeholder">[Vendor First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Vendor Last Name]</span></p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>Designation:&nbsp;</strong></span><span class="placeholder">[Vendor Designation]</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Date:&nbsp;</strong></span><span class="placeholder">[Vendor Signed Date]</span></p><div class="page-break" style="page-break-after:always;"><span style="display:none;">&nbsp;</span></div><p style="margin-left:40px;text-align:center;"><span style="color:hsl(0,0%,0%);"><strong>SCHEDULE I</strong></span></p><p style="margin-left:40px;text-align:center;"><span style="color:hsl(0,0%,0%);"><strong>FORM OF STATEMENT OF WORK</strong></span></p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>THIS STATEMENT OF WORK (“SOW”)</strong> is signed on<strong>&nbsp;</strong></span><span class="placeholder">[Vendor Signed Date]</span><span style="color:hsl(0,0%,0%);">&nbsp;and is made effective from&nbsp;</span><span class="placeholder">[Start Date]</span><span style="color:hsl(0,0%,0%);">&nbsp;<strong>(“Effective Date”)</strong> by and amongst:</span></p><ol style="list-style-type:upper-latin;"><li><span class="placeholder">[Company Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;(UEN No.&nbsp;</span><span class="placeholder">[Company Registration Number]</span><span style="color:hsl(0,0%,0%);">) a company incorporated in India, having its registered office at&nbsp;</span><span class="placeholder">[Company Full Address]</span><span style="color:hsl(0,0%,0%);">&nbsp;(hereinafter referred to as <strong>“Company”</strong>, which expression shall include its successors and permitted assigns);</span></li></ol><p style="margin-left:40px;text-align:center;"><span style="color:hsl(0,0%,0%);"><strong>AND</strong></span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></p><ol style="list-style-type:upper-latin;" start="2"><li><span style="color:hsl(0,0%,0%);">Mr. / Ms.&nbsp;</span><span class="placeholder">[Vendor First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Vendor Last Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;(PAN:&nbsp;</span><span class="placeholder">[Vendor PAN]</span><span style="color:hsl(0,0%,0%);">) (<strong>“Consultant”</strong>) and currently residing at&nbsp;</span><span class="placeholder">[Vendor Full Address]</span><span style="color:hsl(0,0%,0%);">.&nbsp;</span></li></ol><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>WHEREAS:</strong></span></p><ol style="list-style-type:upper-latin;"><li><span style="color:hsl(0,0%,0%);"><strong>The Company and the Consultant have executed a Consultant Agreement dated&nbsp;</strong></span><span class="placeholder">[Start Date]</span><span style="color:hsl(0,0%,0%);">&nbsp;<strong>(“Agreement”)</strong> to, inter alia, govern all the transactions relating to provision of Services by the Consultant to the Company.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Company wishes to avail certain Services from the Consultant.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The Parties hereby execute this SOW to confirm and record the terms and conditions for provision of certain Services by the Consultant to the Company, subject to and in accordance with this SOW and the Agreement.</span><br>&nbsp;</li></ol><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>NOW THE PARTIES HEREBY AGREE AND CONFIRM AS FOLLOWS:</strong></span><br>&nbsp;</p><ol><li><span style="color:hsl(0,0%,0%);">In this SOW, capitalised words and expressions have the meanings given in the Agreement unless otherwise provided herein.&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">This SOW shall be governed by the provisions of the Agreement and all the provisions of the Agreement are incorporated by reference in this SOW. The SOW shall be and form a part of the Agreement.&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);">The provision of Services hereunder by the Consultant to the Company shall be subject to and be governed by the Agreement.</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Description of the Assignment</strong></span><br><br><span class="placeholder">[Assignment Description]</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Scope of Services</strong></span><br><br><span class="placeholder">[Assignment ScopeOfServices]</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Manner of Performance, Specifications and Timelines</strong></span><br><br><span class="placeholder">[Manner Of Performances]</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li><li><span style="color:hsl(0,0%,0%);"><strong>Fee and other Compensation, Manner of Payment</strong></span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol><figure class="table"><table><thead><tr><th style="text-align:center;"><span style="color:hsl(0,0%,0%);">Consultant Role</span></th><th style="text-align:center;"><span style="color:hsl(0,0%,0%);">Currency</span></th><th style="text-align:center;"><span style="color:hsl(0,0%,0%);">Rate</span></th><th style="text-align:center;"><span style="color:hsl(0,0%,0%);">Payment Cycle</span></th></tr></thead><tbody><tr><td style="text-align:center;"><span class="placeholder">[Vendor Role]</span></td><td style="text-align:center;"><span class="placeholder">[Vendor Currency]</span></td><td style="text-align:center;"><span class="placeholder">[Vendor Rate]</span></td><td style="text-align:center;"><span class="placeholder">[Vendor Payment Frequency]</span></td></tr></tbody></table></figure><ol start="8"><li><span style="color:hsl(0,0%,0%);"><strong>Other terms (if any)</strong></span><br><br><span class="placeholder">[Special Clause]</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></li></ol><div class="page-break" style="page-break-after:always;"><span style="display:none;">&nbsp;</span></div><p style="margin-left:40px;"><br><span style="color:hsl(0,0%,0%);"><strong>IN WITNESS WHEREOF, THE PARTIES HAVE ENTERED INTO THIS AGREEMENT THE DAY AND YEAR FIRST ABOVE WRITTEN</strong></span></p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);">Signed and delivered for and on behalf of&nbsp;</span><span class="placeholder">[Company Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;by:</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span class="placeholder">[Client Signature]</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>Name:</strong>&nbsp;</span><span class="placeholder">[Client First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Client Last Name]</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Designation:</strong>&nbsp;</span><span class="placeholder">[Client Designation]</span></p><p style="margin-left:40px;"><br><span style="color:hsl(0,0%,0%);"><strong>Date:&nbsp;</strong></span><span class="placeholder">[Client Signed Date]</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);">Signed and delivered by the Consultant</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span class="placeholder">[Vendor Signature]</span></p><p style="margin-left:40px;">&nbsp;</p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>Name:&nbsp;</strong></span><span class="placeholder">[Vendor First Name]</span><span style="color:hsl(0,0%,0%);">&nbsp;</span><span class="placeholder">[Vendor Last Name]</span></p><p style="margin-left:40px;"><span style="color:hsl(0,0%,0%);"><strong>Designation:&nbsp;</strong></span><span class="placeholder">[Vendor Designation]</span><br><br><span style="color:hsl(0,0%,0%);"><strong>Date:&nbsp;</strong></span><span class="placeholder">[Vendor Signed Date]</span></p><p>&nbsp;</p><p style="text-align:right;"><br><span style="color:hsl(0,0%,0%);">&nbsp;&nbsp;</span><br><span style="color:hsl(0,0%,0%);">&nbsp;</span></p>`;

export const _globalPlaceholders = [
  {
    __typename: 'TemplateValuesOutput',
    key: 'companyName',
    type: 'String',
    label: 'Company Name',
    exampleValue: 'Acme Corporation',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'client.companyName',
    },
    description: "Company's Name, e.g. Acme Corporation",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'companyRegistrationNumber',
    type: 'String',
    label: 'Company Registration Number',
    exampleValue: 'SKDSGCIN1231999',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'client.registrationNumber',
    },
    description: "Company's Registration Number, e.g. SKDSGCIN1231999",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'companyFullAddress',
    type: 'Address',
    label: 'Company Full Address',
    exampleValue: 'Skuad Gurgaon',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'client.address',
    },
    description: "Company's Office Address with zipcode and country, e.g. Skuad Gurgaon",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'geography',
    type: 'Array',
    label: 'Geography',
    exampleValue: 'IN',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: '0',
      conditionKey: null,
      conditionValue: null,
      target: 'geography',
    },
    description: "Contractor's Geography e.g. IN",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientFirstName',
    type: 'String',
    label: 'Client First Name',
    exampleValue: 'Jane',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'CLIENT',
      target: 'firstName',
    },
    description: "Client's First Name e.g. Jane",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientLastName',
    type: 'String',
    label: 'Client Last Name',
    exampleValue: 'Doe',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'CLIENT',
      target: 'lastName',
    },
    description: "Client's Last Name, e.g. Doe",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientEmail',
    type: 'Email',
    label: 'Client Email',
    exampleValue: 'jane.doe@acme.com',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'CLIENT',
      target: 'email',
    },
    description: "Client's email e.g. jane.doe@acme.com",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientDesignation',
    type: 'String',
    label: 'Client Designation',
    exampleValue: 'CHRO',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'CLIENT',
      target: 'designation',
    },
    description: "Client's designation e.g. CHRO",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientInitials',
    type: 'Initials',
    label: 'Client Initials',
    exampleValue: 'J.D.',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: '{i:client:clientInitials}',
    },
    description: "Client's Intials , e.g. J.D.",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorFirstName',
    type: 'String',
    label: 'Vendor First Name',
    exampleValue: 'Jon',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'VENDOR',
      target: 'firstName',
    },
    description: "Vendor's First Name e.g. Jon",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorLastName',
    type: 'String',
    label: 'Vendor Last Name',
    exampleValue: 'Doe',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'VENDOR',
      target: 'lastName',
    },
    description: "Vendor's Last Name, e.g. Doe",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorEmail',
    type: 'Email',
    label: 'Vendor Email',
    exampleValue: 'jon.doe@skuad.io',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'VENDOR',
      target: 'email',
    },
    description: "Vendor's email e.g. jon.doe@skuad.io",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorDesignation',
    type: 'String',
    label: 'Vendor Designation',
    exampleValue: 'Developer',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'recipients',
      conditionKey: 'role',
      conditionValue: 'VENDOR',
      target: 'designation',
    },
    description: "Vendor's designation e.g. Developer",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorInitials',
    type: 'Initials',
    label: 'Vendor Initials',
    exampleValue: 'J.D',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: '{i:vendor:vendorInitials}',
    },
    description: "Vendor's Intials , e.g. J.D.",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorPAN',
    type: 'String',
    label: 'Vendor PAN',
    exampleValue: 'ARMPN1134R',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'vendor.panId',
    },
    description: "Vendor's PAN, e.g. ARMPN1134R",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorHSNcode',
    type: 'String',
    label: 'Vendor HSN Code',
    exampleValue: 'ARMPN1134R',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'vendor.hsnCode',
    },
    description: "Vendor's HsnCode, e.g. ARTU45678",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorFullAddress',
    type: 'Address',
    label: 'Vendor Full Address',
    exampleValue: '65-67, Gurgaon, Haryana, India, 122001',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'vendor.address',
    },
    description: "Vendor's Home Address with zipcode and country, e.g.65-67, Gurgaon, Haryana, India, 122001",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'startDate',
    type: 'Date',
    label: 'Start Date',
    exampleValue: '2022-04-01',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.startDate',
    },
    description: "Contractor's start date of contract, e.g. 2022-04-01",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'terminationDate',
    type: 'Date',
    label: 'Termination Date',
    exampleValue: '2099-04-01',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.terminationDate',
    },
    description: "Contractor's termination date of contract, e.g. 2099-04-01",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'scopeOfWork',
    type: 'String',
    label: 'Scope of Work',
    exampleValue: 'Scope of work',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.scopeOfWork.value',
    },
    description: "Contractor's Scope of work , e.g. Scope of work",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'noticePeriod',
    type: 'Number',
    label: 'Notice Period',
    exampleValue: '10',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.noticePeriod',
    },
    description: "Contractor's notice period to be served , e.g. 10",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'specialClause',
    type: 'String',
    label: 'Special Clause',
    exampleValue: 'Any special clause in the contract',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.specialClause',
    },
    description: 'e.g. Any special clause in the contract',
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'assignmentDomain',
    type: 'String',
    label: 'Assignment Domain',
    exampleValue: 'Contract assignment info domain',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.assignmentInfo.domain',
    },
    description: 'e.g. Contract assignment info domain',
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'assignmentDescription',
    type: 'String',
    label: 'Assignment Description',
    exampleValue: 'Contract assignment info description',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.assignmentInfo.description',
    },
    description: 'e.g. Contract assignment info description',
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'assignmentScopeOfServices',
    type: 'String',
    label: 'Assignment ScopeOfServices',
    exampleValue: 'Contract assignment info Scope Of Services',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.assignmentInfo.scopeOfServices',
    },
    description: 'e.g. Contract assignment info scopeOfServices',
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'mannerOfPerformances',
    type: 'String',
    label: 'Manner Of Performances',
    exampleValue: 'Contract assignment info mannerOfPerformances and Timelines',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: 'meta.assignmentInfo.mannerOfPerformances',
    },
    description: 'e.g. Contract assignment info mannerOfPerformances and Timelines',
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorRole',
    type: 'String',
    label: 'Vendor Role',
    exampleValue: 'Developer',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'contractCompensations',
      conditionKey: null,
      conditionValue: null,
      target: 'role',
    },
    description: "Vendor's Role , e.g. Developer",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorCurrency',
    type: 'String',
    label: 'Vendor Currency',
    exampleValue: 'USD',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'contractCompensations',
      conditionKey: null,
      conditionValue: null,
      target: 'currencyCode',
    },
    description: "Vendor's Currency , e.g. USD",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorRate',
    type: 'Number',
    label: 'Vendor Rate',
    exampleValue: '1800',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'contractCompensations',
      conditionKey: null,
      conditionValue: null,
      target: 'netPayableAmount',
    },
    description: "Vendor's Rate , e.g. 1800",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorPaymentFrequency',
    type: 'Enum',
    label: 'Vendor Payment Frequency',
    exampleValue: 'Every Month',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'contractCompensations',
      conditionKey: null,
      conditionValue: null,
      target: 'paymentFrequency',
    },
    description: "Vendor's Payment Frequency , e.g. Every Month",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorPaymentMadeOn',
    type: 'Date',
    label: 'Vendor Payment MadeOn',
    exampleValue: 'July 27, 2022',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: true,
      path: 'contractCompensations',
      conditionKey: null,
      conditionValue: null,
      target: 'nextPaymentDate',
    },
    description: "Contractor's Made On , e.g. July 27, 2022",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientSignedDate',
    type: 'SignedDate',
    label: 'Client Signed Date',
    exampleValue: '2022-04-01',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: '{d:client:clientSignedDate}',
    },
    description: "Client's start date of contract, e.g. 2022-04-01",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorSignedDate',
    type: 'SignedDate',
    label: 'Vendor Signed Date',
    exampleValue: '2022-04-01',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: '{d:vendor:vendorSignedDate}',
    },
    description: "Vendor's signed date of contract, e.g. 2022-04-01",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'clientSignature',
    type: 'Signature',
    label: 'Client Signature',
    exampleValue: 'Jane Doe',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: '{s:client:clientSignature}',
    },
    description: "Client's signature, e.g. Jane Doe",
  },
  {
    __typename: 'TemplateValuesOutput',
    key: 'vendorSignature',
    type: 'Signature',
    label: 'Vendor Signature',
    exampleValue: 'Jon Doe',
    mapping: {
      __typename: 'TemplateValuesMappingOutput',
      isPreview: false,
      path: null,
      conditionKey: null,
      conditionValue: null,
      target: '{s:vendor:vendorSignature}',
    },
    description: "Vendor's Signature, e.g. Jon Doe",
  },
];
